2025-01-10 19:35:10.469455: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-01-10 19:35:11.533722: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
C:\Users\rites\anaconda3\Lib\site-packages\keras\src\layers\reshaping\flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)
2025-01-10 19:35:15.174202: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated. 
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below: 
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-01-10 19:35:15,299 - DEPRECATED FEATURE: flwr.client.start_numpy_client() is deprecated. 
	Instead, use `flwr.client.start_client()` by ensuring you first call the `.to_client()` method as shown below: 
	flwr.client.start_client(
		server_address='<IP>:<PORT>',
		client=FlowerClient().to_client(), # <-- where FlowerClient is of type flwr.client.NumPyClient object
	)
	Using `start_numpy_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
[93mWARNING [0m:   DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-01-10 19:35:15,299 - DEPRECATED FEATURE: flwr.client.start_client() is deprecated.
	Instead, use the `flower-supernode` CLI command to start a SuperNode as shown below:

		$ flower-supernode --insecure --superlink='<IP>:<PORT>'

	To view all available options, run:

		$ flower-supernode --help

	Using `start_client()` is deprecated.

            This is a deprecated feature. It will be removed
            entirely in future versions of Flower.
        
2025-01-10 19:35:15,318 - Opened insecure gRPC connection (no certificates were passed)
2025-01-10 19:35:15,318 - ChannelConnectivity.IDLE
2025-01-10 19:35:15,318 - ChannelConnectivity.CONNECTING
2025-01-10 19:35:15,327 - ChannelConnectivity.READY
[92mINFO [0m:      
2025-01-10 19:35:15,334 - 
[92mINFO [0m:      Received: get_parameters message aadd5ddc-0c3d-4899-9d11-35d0baa5f74f
2025-01-10 19:35:15,334 - Received: get_parameters message aadd5ddc-0c3d-4899-9d11-35d0baa5f74f
[91mERROR [0m:     Client raised an exception.
Traceback (most recent call last):
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\app.py", line 572, in start_client_internal
    reply_message = client_app(message=message, context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\message_handler\message_handler.py", line 119, in handle_legacy_message_from_msgtype
    get_parameters_res = maybe_call_get_parameters(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\client.py", line 204, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\numpy_client.py", line 214, in _get_parameters
    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MnistClient.get_parameters() got an unexpected keyword argument 'config'
2025-01-10 19:35:15,337 - Client raised an exception.
Traceback (most recent call last):
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\app.py", line 572, in start_client_internal
    reply_message = client_app(message=message, context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\message_handler\message_handler.py", line 119, in handle_legacy_message_from_msgtype
    get_parameters_res = maybe_call_get_parameters(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\client.py", line 204, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\numpy_client.py", line 214, in _get_parameters
    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MnistClient.get_parameters() got an unexpected keyword argument 'config'
2025-01-10 19:35:15,557 - gRPC channel closed
Traceback (most recent call last):
  File "D:\BE Project\application\fl-app\client.py", line 61, in <module>
    fl.client.start_numpy_client(server_address="127.0.0.1:8080", client=client)
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\app.py", line 739, in start_numpy_client
    start_client(
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\app.py", line 200, in start_client
    start_client_internal(
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\app.py", line 579, in start_client_internal
    raise ex
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\app.py", line 572, in start_client_internal
    reply_message = client_app(message=message, context=context)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\client_app.py", line 143, in __call__
    return self._call(message, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\client_app.py", line 126, in ffn
    out_message = handle_legacy_message_from_msgtype(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\message_handler\message_handler.py", line 119, in handle_legacy_message_from_msgtype
    get_parameters_res = maybe_call_get_parameters(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\client.py", line 204, in maybe_call_get_parameters
    return client.get_parameters(get_parameters_ins)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rites\anaconda3\Lib\site-packages\flwr\client\numpy_client.py", line 214, in _get_parameters
    parameters = self.numpy_client.get_parameters(config=ins.config)  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: MnistClient.get_parameters() got an unexpected keyword argument 'config'
